### ISSUE TITLE
Cannot enable subatomic-high-contrast

### ISSUE THREAD

**Issue by kuwze** [cryon/subatomic#20]
I am currently using the following code:
```
(use-package subatomic-theme
  :ensure t
  :config
  (load-theme 'subatomic-high-contrast t))
```

but when opening I get:

> Error (use-package): subatomic-theme :config: Unable to find theme file for ‘subatomic-high-contrast’

Then I tried:
```
(use-package subatomic-theme
  :ensure t
  :config
  (load-theme 'subatomic t))
```

Upon reading the docs it seemed like I should be setting `M-x customize-group subatomic` and toggle "Subatomic High Contrast" to enabled (which I have). But after doing so only subatomic loads, not the high-contrast version.

How do I enable the high-contrast version?

**Comment by cryon** [comment]
Yes, there is not `subatomic-high-contrast` theme, only the customization. I'm not useing `use-package` myself, but perhaps it overwrites any customizations you have made? Or perhaps you didn't save the customize-group buffer?

I tried `M-x customize-group RET subatomic RET`, toggled high contrast mode to on, saved the buffer `C-x C-s`and reloaded the theam `M-x load-theme RET subatomic RET`and it worked.

I haven't tried this, but perhaps it works:
```(use-package subatomic-theme
  :ensure t
  :init
  (setq subatomic-high-contrast t)
  :config
  (load-theme 'subatomic t))
```
